services:
  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    healthcheck:
      test: ["CMD", "curl", "influxdb:8086/api/v2/ping"]
      interval: 3s
      timeout: 10s
      retries: 30

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/var/lib/grafana
    healthcheck:
      test: ["CMD", "grafana-cli", "plugins", "ls"]
      interval: 3s
      timeout: 10s
      retries: 30
